### ISSUE TITLE
Label include links

### ISSUE THREAD

**Issue by arush0311** [Pomax/react-formbuilder#35]
Can we [dangerouslysetinnerhtml](https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml) for field's label? It will help with https://github.com/mozilla/network-pulse/issues/599. The affected code would be https://github.com/Pomax/react-formbuilder/blob/master/src/Form.jsx#L142 i think

A little better would be if we could include a user defined react component provided dynamically into a particular field. could help with https://github.com/mozilla/network-pulse/issues/493

**Comment by Pomax** [comment]
There is a reason it's called "dangerously set innerHTML" is because it's literally that: a dangerous way to set arbitrary HTML, which is why we're creating the label using safe, regular JSX templating instead.

Thankfully, label already lets you do the right thing here: as per https://github.com/Pomax/react-formbuilder/blob/master/src/fields/field-type.js#L25-L28 a label can be either "plain text" or "another React element" so instead of supplying a text string for the help description, simply pass a `<Link>` element and all is well.
